[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='f1345ff25aef86efaf754150e2c8009f33252fba0ea4dd56e55cfe557856467e'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
